#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
generated_path="/tmp/subman-worker-configuration.generated.d.ts"
log_path="/tmp/subman-wrangler-types.log"
registry_path="/tmp/subman-wrangler-registry"
output_path="$repo_dir/src/worker-configuration.d.ts"

cleanup() {
	rm -f "$generated_path" "$log_path"
}
trap cleanup EXIT

WRANGLER_LOG_PATH="$log_path" \
	WRANGLER_REGISTRY_PATH="$registry_path" \
	bunx wrangler types "$generated_path" \
		--config "$repo_dir/wrangler.toml" \
		--include-runtime=false \
		>/dev/null

normalized_path="${generated_path}.normalized"
awk '
NR == 1 {
	print
	print "// Generated by scripts/generate-worker-types.sh from wrangler.toml."
	next
}
/^\/\/ Generated by Wrangler/ { next }
/^[[:space:]]*mainModule: typeof import\(/ { next }
/^[[:space:]]*WORKSPACE_COORDINATOR:/ {
	print "\t\tWORKSPACE_COORDINATOR: DurableObjectNamespace<import(\"./lib/server/workspace-coordinator\").WorkspaceCoordinator>;"
	next
}
{
	print
}
' "$generated_path" >"$normalized_path"
mv "$normalized_path" "$generated_path"
bunx biome format --write "$generated_path" >/dev/null

if [[ "${1:-}" == "--check" ]]; then
	if ! cmp -s "$generated_path" "$output_path"; then
		echo "Worker types are out of date. Run bun run generate:worker-types." >&2
		diff -u "$output_path" "$generated_path" || true
		exit 1
	fi
	exit 0
fi

cp "$generated_path" "$output_path"
