#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
temporary_dir="$(mktemp -d "${TMPDIR:-/tmp}/subman-worker-types.XXXXXX")"
generated_path="$temporary_dir/worker-configuration.d.ts"
log_path="$temporary_dir/wrangler-types.log"
registry_path="$temporary_dir/wrangler-registry"
output_path="$repo_dir/src/worker-configuration.d.ts"

cleanup() {
	rm -rf "$temporary_dir"
}
trap cleanup EXIT

WRANGLER_LOG_PATH="$log_path" \
	WRANGLER_REGISTRY_PATH="$registry_path" \
	bunx wrangler types "$generated_path" \
		--config "$repo_dir/wrangler.toml" \
		--include-runtime=false \
		>/dev/null

normalized_path="${generated_path}.normalized"
awk '
NR == 1 {
	print
	print "// Generated by scripts/generate-worker-types.sh from wrangler.toml."
	next
}
/^\/\/ Generated by Wrangler/ { next }
# GlobalProps describes exports from the generated framework entrypoint. It is
# absent before a build; Env below retains the typed Durable Object binding.
/^[[:space:]]*interface GlobalProps \{/ { in_global_props = 1; next }
in_global_props {
	if (/^[[:space:]]*\}/) in_global_props = 0
	next
}
/^[[:space:]]*WORKSPACE_COORDINATOR:/ {
	print "\t\tWORKSPACE_COORDINATOR: DurableObjectNamespace<import(\"./lib/server/workspace-coordinator\").WorkspaceCoordinator>;"
	next
}
{
	print
}
' "$generated_path" >"$normalized_path"
mv "$normalized_path" "$generated_path"
bunx biome format --write "$generated_path" >/dev/null

if [[ "${1:-}" == "--check" ]]; then
	if ! cmp -s "$generated_path" "$output_path"; then
		echo "Worker types are out of date. Run bun run generate:worker-types." >&2
		diff -u "$output_path" "$generated_path" || true
		exit 1
	fi
	exit 0
fi

cp "$generated_path" "$output_path"
