/* eslint-disable */
// Generated by scripts/generate-worker-types.sh from wrangler.toml.
declare namespace Cloudflare {
	interface Env {
		ASSETS: Fetcher;
		WORKSPACE_COORDINATOR: DurableObjectNamespace<
			import("./lib/server/workspace-coordinator").WorkspaceCoordinator
		>;
	}
}
interface Env extends Cloudflare.Env {}
