/* eslint-disable */
// Generated by scripts/generate-worker-types.sh from wrangler.toml.
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	WORKSPACE_COORDINATOR: DurableObjectNamespace<
		import("./lib/server/workspace-coordinator").WorkspaceCoordinator
	>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		durableNamespaces: "WorkspaceCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
